# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41447499eda2bf855c1228615b072730640355bf90f6a9c8bf2b77bc05459d5e2532a9e93fe5768f142aca4f9b52d6b5766b5bbc270054bbeee3489631e5b19e

test:
  secret_key_base: b28a5772aef4969b9e464316be7e16dbf38437ac9e08b97603e3f8ea4c446373db615a0f5e43d0600fe0e58c3fb21f21b93929b7ba92f9fb268db82bd835f92b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
